version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    labels:
      service: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
    name: mosquitto-data
    labels:
      service: mosquitto
  mosquitto-log:
    name: mosquitto-log
    labels:
      service: mosquitto

networks:
  default:
    name: mosquitto
    labels:
      service: mosquitto
